import type { Metadata } from 'next'
import LegalShell from '../LegalShell'

export const metadata: Metadata = { title: 'Privacy Policy', description: 'How Webmaster Global collects, uses, protects, and handles personal information worldwide.', alternates: { canonical: '/privacy' } }

export default function PrivacyPage() {
  return <LegalShell eyebrow="GLOBAL PRIVACY NOTICE" title="Privacy Policy">
    <section><h2>Who we are</h2><p>Webmaster Global provides digital product, website, e-commerce, frontend, automation, and AI integration services worldwide. This notice explains how information is handled when you visit this website or submit a project inquiry.</p></section>
    <section><h2>Information we collect</h2><p>When you contact us, we may collect the name, contact details, company, project type, budget range, engagement preference, and project description you choose to provide. Security records may include limited technical information such as an IP-derived hash, request time, browser details, and anti-spam signals. If you approve analytics cookies, Google Analytics may process device, interaction, approximate location, and usage information.</p></section>
    <section><h2>Why we use it</h2><ul><li>To respond to inquiries, assess projects, and provide requested services.</li><li>To prevent spam, abuse, duplicate submissions, and security attacks.</li><li>With your consent, to understand website performance and improve content.</li><li>To meet applicable legal obligations and establish or defend legal claims.</li></ul></section>
    <section><h2>Legal bases and choices</h2><p>Depending on your location, processing may rely on your consent, steps requested before entering a contract, performance of a contract, legal obligations, or legitimate interests such as site security. Optional analytics is consent-based and remains disabled until accepted. You can withdraw that consent at any time through “Cookie settings.”</p></section>
    <section><h2>Service providers and international transfers</h2><p>Information may be processed by service providers used to operate the portfolio, including Vercel for hosting, Supabase for inquiry storage and security, and—only after consent—Google Analytics. Their infrastructure may process data outside your country. Appropriate contractual, technical, and legal safeguards should be used where required.</p></section>
    <section><h2>Retention and security</h2><p>Inquiry data is retained only as long as reasonably needed to respond, manage a potential or active engagement, maintain security, and satisfy legal or accounting requirements. Data is protected through access controls, database security policies, validation, rate limiting, and anti-spam measures. No internet service can promise absolute security.</p></section>
    <section><h2>Your regional privacy rights</h2><h3>European Union, EEA, Germany, and United Kingdom</h3><p>You may have rights to access, correct, erase, restrict, object, withdraw consent, receive portable data, and complain to your local supervisory authority. Germany is covered by EU GDPR together with applicable German law; the UK applies its own data-protection and electronic-communications framework.</p><h3>United States</h3><p>Rights vary by state and may include knowing, accessing, correcting, deleting, or obtaining a copy of personal information, and opting out of sale, sharing, targeted advertising, or certain profiling. Webmaster Global does not intend to sell personal information.</p><h3>Canada</h3><p>You may request access to and correction of personal information and withdraw consent, subject to applicable federal or provincial law.</p><h3>India</h3><p>Subject to applicable implementation and exemptions, you may have rights concerning access to information about processing, correction, erasure, grievance handling, and nomination under India’s data-protection framework.</p><h3>Russia</h3><p>Visitors may have rights concerning information, access, correction, blocking, deletion, consent withdrawal, and complaints under applicable Russian data-protection rules. Cross-border and localization requirements may apply depending on the service and processing activity.</p><h3>Other countries and all continents</h3><p>Visitors in Africa, Asia, Europe, North America, South America, Oceania, and Antarctica research operations are welcome to contact us. We will consider applicable local privacy rights where the service is offered, while mandatory local requirements may differ.</p></section>
    <section><h2>Requests and children</h2><p>Use the project inquiry form and write “Privacy request” in the project details to request access, correction, deletion, or consent withdrawal. We may need to verify your identity. This portfolio is intended for business users and is not directed to children.</p></section>
    <section><h2>Policy updates</h2><p>We may update this notice when services, providers, or laws change. The effective date above identifies the current version. This notice is general transparency information and not legal advice.</p></section>
  </LegalShell>
}
